spring.application.name=KidsPartyManager

spring.datasource.url=${MYSQL_CONNECTION_URI}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.database=mysql
spring.jpa.show-sql=true

#For development only - recreates schema and loads data.sql on each start up
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true